#!/bin/bash
#SBATCH -J trial_hpc_batch
#SBATCH -A MRC-BSU-SL2-CPU
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=14
#SBATCH --time=36:00:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=TIME_LIMIT
#SBATCH --mail-type=END
#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
#SBATCH --no-requeue
#SBATCH --verbose

#SBATCH --array=1-2
#SBATCH -p skylake
#SBATCH --qos=covid0


#SBATCH --output=model_runs_20210120regjobs_%a.out
#SBATCH --error=model_runs_20210120regjobs_%a.err

# Navigate to the correct working directory
workdir="$SLURM_SUBMIT_DIR/model_runs/20210120/PrevCevik_NHS60cutoff_11_prev14_matrices_20210115_timeuse_household_adjusted_mean"
if [ $SLURM_ARRAY_TASK_ID -eq 2 ]; then
    workdir="$SLURM_SUBMIT_DIR/model_runs/20210120/PrevCevik_NHS60cutoff_4_prev14_matrices_20210115_timeuse_household_adjusted_mean"
fi

module load gcc/9 intel/compilers/2020.2

echo $workdir

cd $workdir

if [ -f "posterior_report10" ]; then
    echo "existing output found"
else
  ../../../rtm_hpc
fi
