#!/bin/bash
#SBATCH -J post_process_bulk
#SBATCH -A MRC-BSU-SL2-CPU
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=01:00:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=TIME_LIMIT
#SBATCH --mail-type=END
#SBATCH --verbose
#SBATCH --qos=covid0

#SBATCH --array=0-1
#SBATCH -p skylake-himem


#SBATCH --output=post_process_%a.out
#SBATCH --error=post_process_%a.err

module load pandoc
module load R/3.6
dirs=(*/)
cd ${dirs[SLURM_ARRAY_TASK_ID]}
pwd
Rscript ../../../rerun.R
