#!/bin/bash
#SBATCH -J trial_hpc_batch
#SBATCH -A MRC-BSU-SL2-CPU
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=72:00:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=TIME_LIMIT
#SBATCH --mail-type=END
#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
#SBATCH --no-requeue
#SBATCH --verbose

#SBATCH --array=1-6
#SBATCH -p skylake
#SBATCH --qos=covid0


#SBATCH --output=model_runs_20210120regjobs_%a.out
#SBATCH --error=model_runs_20210120regjobs_%a.err

# Navigate to the correct working directory
bp="IFR3bp"
enddays="25"
if (( $SLURM_ARRAY_TASK_ID % 2 == 0 )); then
    days="60"
else
    days="28"
fi
if [ $SLURM_ARRAY_TASK_ID -lt 3 ]; then
    prev="NoPrev"
    gap=""
    pdays=""
else
    prev="Prev"
    pdays="339"
    if [ $SLURM_ARRAY_TASK_ID -lt 5 ]; then
	gap="_prev7-5"
    else
	gap="_prev14-5"
    fi
fi
geog="NHS"
cm="ons"
eff="Nick"

workdir="$SLURM_SUBMIT_DIR/model_runs/20210409/${prev}${pdays}_cm4${cm}_${bp}_${geog}${days}cutoff_${enddays}wk2${gap}${eff}_matrices_20210409_timeuse_household_deaths"

module load gcc/9 intel/compilers/2020.2

echo $workdir

cd $workdir

if [ -f "posterior_report10" ]; then
    echo "existing output found"
else
  ../../../rtm_hpc2
fi
