#!/bin/bash
#SBATCH -J trial_hpc_batch
#SBATCH -A MRC-BSU-SL2-CPU
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=14
#SBATCH --time=36:00:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=TIME_LIMIT
#SBATCH --mail-type=END
#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
#SBATCH --no-requeue
#SBATCH --verbose

#SBATCH --array=1-8
#SBATCH -p skylake
#SBATCH --qos=covid0


#SBATCH --output=model_runs_20201122prevjobs_%a.out
#SBATCH --error=model_runs_20201122prevjobs_%a.err

workdir="$SLURM_SUBMIT_DIR/model_runs/20201122/"

if [ $SLURM_ARRAY_TASK_ID -lt 5 ]; then
    workdir="${workdir}No"
fi
workdir="${workdir}Prev_relax_shortsero_"
if (( $SLURM_ARRAY_TASK_ID % 4 < 2 )); then
    workdir="${workdir}fix_"
fi
workdir="${workdir}cm4_latestart_ifr_"
if (( $SLURM_ARRAY_TASK_ID % 2 == 0 )); then
    workdir="${workdir}28"
else
    workdir="${workdir}60"
fi
workdir="${workdir}cutoff_matrices_20201120_deaths"

module load gcc/9 intel/compilers/2020.2

echo $workdir

cd $workdir

# if [ -f "posterior_report10" ]; then
#     echo "existing output found"
# else
    ../../../rtm_hpc
# fi
