#!/bin/bash
#SBATCH -J hpc-test
#SBATCH -A mrc-bsu-sl2-cpu
#SBATCH -c 9
#SBATCH -t 12:0:0
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=TIME_LIMIT
#SBATCH --mail-type=END
#SBATCH --verbose
#SBATCH --qos=covid0

#SBATCH --array=0
#SBATCH -p skylake

#SBATCH --output=model_runs_%a.out
#SBATCH --error=model_runs_%a.err

module load gcc/9 intel/compilers/2019.4 gsl-2.4-intel-17.0.4-etauzbm
dirs=(*/)
cd ${dirs[SLURM_ARRAY_TASK_ID]}
pwd
../../../rtm_hpc
sbatch ../../../submit_post_process_correct_dir