#!/bin/bash
#SBATCH -J trial_hpc_batch
#SBATCH -A MRC-BSU-SL2-CPU
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=27
#SBATCH --time=48:00:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=TIME_LIMIT
#SBATCH --mail-type=END
#SBATCH --verbose
#SBATCH --qos=covid0
#SBATCH --exclusive

#SBATCH --array=1
#SBATCH -p skylake


#SBATCH --output=model_runs.out
#SBATCH --error=model_runs.err

module load gcc/9 intel/compilers/2020.2 gsl
../../../rtm_hpc2
sbatch ../../../submit_post_process_correct_dir
