#!/bin/bash
#SBATCH -J trial_hpc_batch
#SBATCH -A MRC-BSU-SL2-CPU
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=12:00:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=TIME_LIMIT
#SBATCH --mail-type=END
#SBATCH --verbose
#SBATCH --qos=covid0

#SBATCH --array=0-5
#SBATCH -p skylake

#SBATCH --output=model_runs_%a.out
#SBATCH --error=model_runs_%a.err

module load intel/bundles/complib/2020.2 gsl-2.4-intel-17.0.4-etauzbm gcc-5.4.0-gcc-4.8.5-fis24gg
dirs=(*/)
cd ${dirs[SLURM_ARRAY_TASK_ID]}
pwd
../../../rtm_hpc2

