#!/bin/bash
#SBATCH --job_name=testrunRTM
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=00:03:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL,TIME_LIMIT,END
#SBATCH --mail-user=joel.kandiah@phe.gov.uk
#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
#SBATCH --no-requeue
#SBATCH --verbose


#SBATCH --output=model_runs_20210120regjobs_%a.out
#SBATCH --error=model_runs_20210120regjobs_%a.err

module load gcc/gcc-9.4.0 gsl openmp openmpi OpenBLAS R 

## dirs=(*/)
## cd ${dirs[SLURM_ARRAY_TASK_ID]}
## pwd

if [ -f "posterior_report10" ]; then
    echo "existing output found"
else
  ../../rtm_hpc2
fi
  # sbatch ../../../submit_post_process_correct_dir

