#!/bin/bash

#SBATCH --nodes=1
#! How many (MPI) tasks will there be in total? (<= nodes*16)
#SBATCH --ntasks=1
#! How many CPUs will each task require
#SBATCH --cpus-per-task=2
#! How much wallclock time will be required?
#SBATCH --time=0:20:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL,TIME_LIMIT,END
#SBATCH --mail-user=joel.kandiah@phe.gov.uk
#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
#SBATCH --no-requeue
#SBATCH --verbose
#SBATCH --array=1,3,6,7
#SBATCH --output=submit_save_endstates_%a_%j.out
#SBATCH --error=submit_save_endstates_%a_%j.err

module load R gcc openmp intel_compiler OpenBLAS openmpi slurm

dirs=(*/)
pwd
application="Rscript"
options="~/mcmc/real-time-mcmc/R/output/save_end_state.R"
CMD="$application $options ${dirs[SLURM_ARRAY_TASK_ID]}"
# echo "${dirs[SLURM_ARRAY_TASK_ID]}/posterior_report10"
# if [ -e "${dirs[SLURM_ARRAY_TASK_ID]}/posterior_report10" ]; then
#     echo "Running $CMD"
  eval $CMD
  # sbatch 
# fi
