#!/bin/bash
#SBATCH -J trial_hpc_batch
#SBATCH -A MRC-BSU-SL2-CPU
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=23:00:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=TIME_LIMIT
#SBATCH --mail-type=END
#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
#SBATCH --no-requeue
#SBATCH --verbose

#SBATCH --array=0,3,8,11
#SBATCH -p cclake
#!SBATCH --qos=covid0


#SBATCH --output=model_runs_20210120regjobs_%a.out
#SBATCH --error=model_runs_20210120regjobs_%a.err

module load intel/bundles/complib/2020.2 gsl-2.4-intel-17.0.4-etauzbm gcc-5.4.0-gcc-4.8.5-fis24gg

dirs=(*/)
cd ${dirs[SLURM_ARRAY_TASK_ID]}
pwd

if [ -f "posterior_report10" ]; then
    echo "existing output found"
else
  ../../../rtm_hpc2
  # sbatch ../../../submit_post_process_correct_dir
fi
