#!/bin/bash
#SBATCH --job_name=testrunRTM
#SBATCH --nodes=3
#SBATCH --ntasks-per-node=3
#SBATCH --cpus-per-task=2
#SBATCH --time=00:05:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL,TIME_LIMIT,END
#SBATCH --mail-user=joel.kandiah@phe.gov.uk
#SBATCH --mail-user=joel.kandiah@phe.gov.uk
#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
#SBATCH --no-requeue
#SBATCH --verbose

#SBATCH --output=model_runs_20210120regjobs_%a.out
#SBATCH --error=model_runs_20210120regjobs_%a.err

module load gcc R openmpi slurm

# sintr -N1 -n1 -c4 -t 1:0:0 --qos=INTR


# ls -a
# module list
# echo $LD_LIBRARY_PATH

# ## dirs=(*/)
# ## cd ${dirs[SLURM_ARRAY_TASK_ID]}
# ## pwd


mpirun Rscript hello.R

  # sbatch ../../../submit_post_process_correct_dir

