#!/bin/bash
#SBATCH --job_name=inputs_process_rtm
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --time=04:30:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL,TIME_LIMIT,END
#SBATCH --mail-user=joel.kandiah@phe.gov.uk
#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
#SBATCH --no-requeue
#SBATCH --verbose
#SBATCH --mem=20G
#SBATCH --output=model_runs_20210120regjobs_%a.out
#SBATCH --error=model_runs_20210120regjobs_%a.err

module load R gcc

# sintr -N1 -n1 -c4 -t 1:0:0 --qos=INTR




# ls -a
# module list
# echo $LD_LIBRARY_PATH

# ## dirs=(*/)
# ## cd ${dirs[SLURM_ARRAY_TASK_ID]}
# ## pwd


Rscript ./run.R

  # sbatch ../../../submit_post_process_correct_dir

