### `r Dta.text` incidence {.tabset}

#### By region
```{r reg-death, cache=TRUE, cache.extra=results_hash}
dth.file <- file.path(out.dir, "deaths_data.RData")
if (is.null(dth.dat) && file.exists(dth.file)){
   load(dth.file)
}
if (!is.null(dth.dat) && is.null(adm.sam)){
   ## Below chunk is a temporary fix
   if("Region" %in% names(dth.dat)) dth.dat <- rename(dth.dat, region = Region)
   if("Age.Grp" %in% names(dth.dat)) dth.dat <- rename(dth.dat, age = Age.Grp)
   if("n" %in% names(dth.dat)) dth.dat <- rename(dth.dat, value = n)
   dth.dat <- dth.dat %>% filter(date <= start.date + end.hosp - 1)
   dth.dat$age <- recode(dth.dat$age, `>=75` = "75+", `0-44` = "<45")
}
make.plots(noisy_deaths, by = "region", data = dth.dat, project.forwards = TRUE, x.label = "Date of death")
```

#### By age
```{r age-death, cache=TRUE, cache.extra=results_hash}
make.plots(noisy_deaths, by = "age", data = dth.dat, project.forwards = TRUE, x.label = "Date of death")
```

### Cumulative `r dta.text` {.tabset}

#### By region
```{r cum-reg-death, cache=TRUE, cache.extra=results_hash}
make.plots(cum_deaths, by = "region", project.forwards = TRUE, x.label = "Date of death")
```

#### By age
```{r cum-age-death, cache=TRUE, cache.extra=results_hash}
make.plots(cum_deaths, by = "age", project.forwards = TRUE, x.label = "Date of death")
```
