### Prevalence {.tabset}

#### By region
```{r reg-prevalence, cache=TRUE, cache.extra=results_hash}
cat("Got here 1\n")
dim.id <- which(names(dimnames(prevalence)) == "date")
cat("Got here 2\n")
ndate.data <- lubridate::as_date(date.data) - start.date + 1
cat("Got here 3\n")
cat("Prevalence exists is ", exists("prevalence"), " it is an array of dimension", dim(prevalence), "\n")
prev_plot <- R.utils::extract(prevalence, indices = list(start.prev:ndate.data), dims = dim.id)
cat("Got here 4\n")
make.plots(prev_plot, by = "region")
```

#### By age
```{r age-prevalence}}
cat("Got here 5\n")
make.plots(prev_plot, by = "age")
```

#### Goodness-of-fit
```{r reg-prevalence-gof}
cat("Got here 6\n")
prev.dat <- prev.dat %>%
	 filter(sample_date >= start.date - 1 + start.prev,
	 	sample_date <= start.date - 1 + end.prev,
		lsd > 0) %>%
	 rename(date = sample_date)
l.norm.noise <- function(mu, sd, replicates = noise.replicates){
    stopifnot(is.null(dim(drop(sd))))
    lmu <- log(mu)
    return(rlnorm(n = length(lmu) * replicates,
                  meanlog = rep(lmu, each = replicates),
                  sdlog = rep(sd, each = replicates)
                  )
           )
}
cat("Got here 7\n")
prev_gof <- prev_plot %>%
    as.tbl_cube(met_name = "prev") %>%
    as_tibble() %>%
    mutate(date = lubridate::as_date(date)) %>%
    inner_join(prev.dat) %>%
    mutate(sampled = rlnorm(length(prev), log(prev), lsd)) %>%
    group_by(age, date, region, obs = exp(lmean)) %>%
    summarise(q50 = median(sampled),
              qlo = quantile(sampled, 0.025),
              qhi = quantile(sampled, 0.975))

cat("Got here 8\n")
ggplot(prev_gof, aes(y = q50, ymin = qlo, ymax = qhi, x = date, colour = region, group = region)) +
    geom_point(position = position_dodge(8)) +
    geom_linerange(position = position_dodge(8)) +
    facet_wrap(~age, scales="free_y") +
    theme(legend.position = "bottom") +
    geom_point(aes(x=date, y=exp(lmean), group=region), data=prev.dat, colour="black", inherit.aes=FALSE, position=position_dodge(8))
```

<!-- ### Cumulative hospitalisations {.tabset} -->

<!-- #### By region -->
<!-- ```{r} -->
<!-- make.plots(cum_case, by = "region") -->
<!-- ``` -->

<!-- #### By age -->
<!-- ```{r} -->
<!-- make.plots(cum_case, by = "age") -->
<!-- ``` -->
