### Updates

#### Model and report changes

1. The model now accounts for the ongoing immunisation programme, stratifying the population of people still susceptible to infection with the virus according to their immunisation status (unimmunised/1 dose/2 doses). We use data on the daily proportions of the population getting immunised to inform this splitting of the population, assuming that it takes three weeks for vaccine-derived immunity to develop. Vaccine efficacy is assumed against both infection and death, using values for the efficacy in agreement with those found [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/995101/Vaccine_surveillance_report_-_week_24_v2.pdf). We have a changepoint in the vaccine efficacy on the 10th May, which marks a transition from alpha being the dominant variant, to delta.
1. The model now also accounts for a different susceptibility to infection in each adult age group (no prior information is used); and for the under-15s, (using prior information from [Viner et al, 2020](https://jamanetwork.com/journals/jamapediatrics/fullarticle/2771181), which estimates children to be less likely to acquire infection when in contact with an infectious individual).
1. The model has the ability to incorporate estimates of community prevalence, by region and age group, from the Office of National Statistics COVID-19 Infection Survey (see Data Sources for details). These are included weekly since the outset of the Survey in May 2020 for the age groups >4 years to inform trends in incidence that are too recent to be captured by the data on deaths.
1. The geographical definition has been changed from the seven NHS regions ([map](https://www.arcgis.com/sharing/rest/content/items/e4dd34a2d07b43088e17ed73e1bd3357/data)) to the nine regions typically used in government ([map](https://www.arcgis.com/sharing/rest/content/items/738566d958834b70a809dc72a154eaf9/data)). This new spatial definition more appropriately reflects the existing regional heterogeneity.
1. The underlying probability of an unvaccinated individual dying following infection with SARS-CoV2 (the infection-fatality rate, IFR) is allowed to change gradually over the course of 30 days every (approximately) 100 days. This is designed to reflect fluctuations due to seasonal effects, demand on healthcare services or the emergence of new virus variants of differing severity.
1. The ‘Epidemic summary’ now only reports the current value for the IFR by age. To visualise how this has changed over time in our model, see the IFR tab in the ‘Infections and Deaths’ section of the report. The quantity that is now plotted under this tab is the probability of _dying if infected_, taking into account the impact of the immunisation programme.


#### Updated findings

1. The estimate of the daily number of new infections on the 12th July across England is 33,500 (25,700--43,900, 95% credible interval). Incidence is increasing and this represents an upward revision of our most recent published estimate which covered the period to 19th June.
1. The daily infection rate is estimated to be the highest in the North East (NE) with 198 infections per 100K population per day. This corresponds to 5,250 new daily infections. The next highest rates of infection are in the North West (NW) and the West Midlands (WM) with 75 and 72 infections per 100K (5,500 and 4,280 daily infections), respectively. The East Midlands (EM), Yorkshire and Humber (YH), London (GL) and South West (SW) all have between 45--55 new infections per 100k each day. The South East (SE) remains the region with the lowest incidence rate with 27 infections per 100K. Note that a substantial proportion of these daily infections will be asymptomatic.
1. The number of deaths occurring daily has started increasing. For the 2nd August we forecast between 94 and 201 daily deaths, though there is a distinct lack of fit to these data over the past two months with consequent very low confidence in these projections.
1. The probability of Rt exceeding 1 is close to 100% in most regions. It is highest in the NE (97%), GL (95%) and WM (92%); between 80--90% in the SE, YH and NW; between 70--80% in the East of England (EE) and EM and lowest for the SW at 68%.
1. The growth rate for England has risen to 0.02 (0.01–0.03) per day. This means that, nationally, the number of infections is highly likely to be increasing, although these growth estimates are quite uncertain and heterogeneous  across regions. The national rate of growth corresponds to a doubling in the number of new infections every 30.8 days
1. GL, followed by the NE and the WM, have the highest attack rates, that is the proportions of the regional populations who have ever been infected, with 32%, 31% and 28% respectively. The SW continues to have the lowest attack rate at 16%. These attack rates are entirely consistent with our previous published report. 
1. Note that the deaths data used are only very weakly informative on Rt over the last two weeks and are thankfully sparse. Therefore, the estimate for current incidence, Rt and the forecast of daily numbers of deaths are likely to be subject to some revision.

#### Interpretation

The plots of the estimated Rt over the most recent weeks show that the Rt appears to be following a declining trend in the absence of any further major relaxation of pandemic mitigation measures. Of all the regions, the NE had the highest recent peak in Rt of 1.53 (CrI 1.32--1.75) with a subsequent fall to 1.20 (1.00--1.41). This downward trend in R from the peak is still largely driven by the indices of mobility (from Google and school attendance).

From the end of March onwards, the incidence of deaths fell more sharply than predicted by the model, though both data and predicted trends are now showing a gradual rise over recent weeks. This does suggest that the ONS estimates and the data on deaths are giving conflicting signals. While this lack of fit has been reduced this week, further model development is ongoing to rectify this discrepancy.

Plots of the IFR over time show that from the end of January we estimate a decreasing IFR in all adult age groups, but most steeply in the older ages. This drop indicates the benefits of immunisation against death over and above the benefits against infection. Specifically, there is an estimated fall to a still-high 2.2% (1.9%--2.6%) in the over-75s and 0.10% (0.09%--0.11%) overall. The overall impact of the immunisation programme can be seen more clearly in the `All Ages’ plot, where the precipitous decline in IFR since late January is a product of this efficacy against death but also of the increasing proportion of infections in young people; older age groups are immunised and become more protected against infection. The impact of the immunisation in the 25--44 age-group is beginning to become apparent with a fall after an initial plateau.

For context, alongside the data used here, other indicators (e.g. hospital admissions, reported new positive tests) are suggesting a resurgent epidemic, largely due to the increasing dominance and spread of the Delta strain. Prevalence of infection, as estimated by the ONS Coronavirus Infections Survey, is close to 0.6% in England, though there is considerable regional heterogeneity. Again, as we move towards the 19th July and the complete lifting of social-distancing measures with an Rt dropping towards 1, there is the potential for the epidemic to display a range of qualitative behaviours over the coming period. The next few weeks will be crucial. 
